#!/bin/bash

release_file=/etc/os-release
logfile=/var/log/updater.log
errorlog=/var/log/updater_errors.log

# function
check_exit_status(){
       if [ $? -ne 0 ]
            then
                echo "An error occurred , please check the $errorlog file "
        fi
}


if grep -q "Arch" $release_file
    then
        # The host is based on Arch , run pacman update command
        sudo pacman -Syu 1>>$logfile 2>>$errorlog
    check_exit_status
fi

if grep -q "Debian" $release_file || grep -q "Ubuntu" $release_file || grep -q "Kali" $release_file
    then
        # The host is based on  Debian or Ubuntu
        # Run the apt version of the command
        echo "System update ...."
        sleep 3
        sudo apt update -y 1>>$logfile 2>>$errorlog
        check_exit_status

        echo "System upgrade ...."
        sleep 3
        sudo apt dist-upgrade -y 1>>$logfile 2>>$errorlog
        check_exit_status
fi