#!/bin/bash

# is pound symbol

release_file=/etc/os-release

if grep -q "Arch" $release_file
    then
        # The host is based on Arch , run pacman update command
        sudo pacman -Syu
fi

if grep -q "Debian" $release_file || grep -q "Ubuntu" $release_file || grep -q "Kali" $release_file
    then
        # The host is based on  Debian or Ubuntu
        # Run the apt version of the command
        echo "System update ...."
        sleep 3
        sudo apt update -y
        echo "System upgrade ...."
        sleep 3
        sudo apt dist-upgrade -y
fi