// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace validate {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox t1;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator r1;
		
		protected System.Web.UI.WebControls.TextBox t3;
		
		protected System.Web.UI.WebControls.TextBox t4;
		
		protected System.Web.UI.WebControls.CompareValidator r3;
		
		protected System.Web.UI.WebControls.TextBox t5;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator r4;
		
		protected System.Web.UI.WebControls.ValidationSummary r5;
		
		protected System.Web.UI.WebControls.Button button1;
	}
}
